### ISSUE TITLE
What is the consideration to use Compute engine over app engine for web server?

### ISSUE THREAD

**Issue by xuxiuzhenzhen** [cgswong/webapp-autocomplete#7]
What is the consideration to use Compute engine over app engine for web server?

besides the fact that php7.0 is not supported by app engine

**Comment by cgswong** [comment]
The decision or considerations as to AE vs. CE is based on:

- Control: you have more control over the various knobs with CE, much less with AE. A good example are the supported languages for AE, where with CE it is whatever you want.
- Ease of use: you can get up and running with AE much quicker (a few minutes) than with CE (a few hours). The workflow in terms of making changes, and doing rolling updates is integrated with AE, while with CE you will need to build this yourself.
- Integrations: AE integrates with other services such as caching, load balancing, database which you can easily leverage, while with CE you will need to setup the integrations. This emphasises the previous points.

**Comment by xuxiuzhenzhen** [comment]
Thank you for your response!
Based on your points, 
It seems AE is better solution for the autocomplete server than CE which was selected for this example.
I am still not sure the reason of chosing CE over AE for this one...
I understand if you use redis ( versus memcache) here, you might lean towards CE, seeing AE standard doesnt support redis, but AE flex can still be better alternative

Just reiterate my question, why in this demo , CE was selected for deploy autocomplete server not AE ( flex)?

Thank you so much

**Comment by cgswong** [comment]
AE is a more efficient solution (in my opinion) which is why I choose it over CE. That work is in the `devel` branch as the `master` is just the initial coding work. AE Flex may be better than Standard but for my purposes at the time I did not explore it too deeply.
